Traceback (most recent call last):
  File "PSO-NN.py", line 39, in <module>
    wandb.init(project="4g4-kim-test")
  File "/usr/local/lib/python3.7/site-packages/wandb/__init__.py", line 1113, in init
    as_defaults=not allow_val_change)
  File "/usr/local/lib/python3.7/site-packages/wandb/wandb_config.py", line 298, in _update
    self.persist()
  File "/usr/local/lib/python3.7/site-packages/wandb/wandb_config.py", line 206, in persist
    conf_file.write(str(self))
  File "/usr/local/lib/python3.7/site-packages/wandb/wandb_config.py", line 339, in __str__
    allow_unicode=True, encoding='utf-8')
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/local/lib/python3.7/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/usr/local/lib/python3.7/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/usr/local/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/local/lib/python3.7/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/usr/local/lib/python3.7/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/local/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/usr/local/lib/python3.7/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/usr/local/lib/python3.7/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/usr/local/lib/python3.7/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/usr/local/lib/python3.7/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', OrderedDict([('cli_version', '0.8.31'), ('code_path', 'code/Code/PSO-NN.py'), ('is_jupyter_run', False), ('is_kaggle_kernel', False), ('python_version', '3.7.4'), ('framework', 'keras')]))
